### PR TITLE
Adds a "Forums excluded from counts" setting.

### PR DESCRIPTION
**Pull request by lairdshaw**
We wanted this functionality for a forum I help administer - hopefully
you guys are willing to incorporate it in this official repo. I'm happy to
make modifications as required/suggested.

The (hopefully self-explanatory) description of the new setting is: "Select
forums in which you do not want any Thank yous/Likes to count towards
any member's publicly visible count of given and received Thank
yous/Likes (only forums - no categories!)."

Use case (an actual scenario): You have a private forum for forum
administrators. You want administrators to be able to like one another's
posts in this forum, but you don't want those likes to count towards
their publicly visible totals (and, presumably, as in the actual
scenario, you want to prevent posts and threads in the private forum
from counting towards their publicly visible post+thread counts).

Note: Does not modify the search code at all, so searching for a
member's liked/liked-for posts may show more posts than the counts
beside his/her name if the searcher has permission to view the excluded
forums.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Nice addition, seems to be really useful for some boards. @svepu can you please review and merge? Thank you!

@lairdshaw any more ideas? Are you good at javascript, there are two issues which needs someone familiar with JS to incorporate, if you will have some free time please check them and let us know, thank you

**Comment by Eldenroot** [comment]
Maybe would be better to have all code in one file and do not create a new one if it is possible.

**Comment by lairdshaw** [comment]
@Eldenroot, you're right - I've removed that extra file and moved its function into the main plugin file.

Re Javascript, I can code a little in it - which issues would you like me to look at in particular?

**Comment by SvePu** [comment]
@Eldenroot - I'll check it tomorrow on my PC .... @lairdshaw .... code looks very nice...Thx

**Comment by SvePu** [comment]
PR is merged .... Thx @lairdshaw

**Pull request merged**
