### PR TITLE
Fixes #140

### LINKED ISSUE #140: jGowl popup notification - thanks/likes remaining
As mentioned here - add thanks/likes remaining notice in popup window
#25

### PR DESCRIPTION
**Pull request by lairdshaw**
Fixes #140

@Eldenroot, I didn't look at DarkNeo's plugin but see if this does what you want.

### CODE REVIEW

**Comment by Eldenroot** [comment]
What if the user has unlimited thanks/like? New lang variable is needed?

**Comment by lairdshaw** [comment]
Well, it's not a new popup, I just appended onto the popup which already had the message "Adding [Like/Thank You] to this post", so right now if the user has unlimited thanks/likes, then all that happens is that nothing is appended - no need to hide anything. But if you want, we can instead append "You have unlimited likes remaining" or something like that.

**Comment by Eldenroot** [comment]
Maybe we can add a support for that, so every user (admin) can just change or delete lang/adjust text for this output variable (or leave it as it is).

However maybe it would be just too complicated and we should use this easiest way instead.

**Comment by lairdshaw** [comment]
Added - how does this seem to you? (Admittedly, the hard-coded value of 12000 is ugly).

**Comment by Eldenroot** [comment]
It seems to be fine, thank you. About hard coded value - what do you suggest, leave it and just adjust the time?

I will wait to @svepu - he will review and merge into master. 

Thank you very much! Can you check the last issue - antiflood? It would require one acp setting - on/off and load one js file if I right (js can be used from post rate as a working example).

**Comment by lairdshaw** [comment]
I turned it into a constant at the top of the file pending a better suggestion. Plus, I fixed the calculation of likes remaining - I had it showing the limit rather than number remaining.

Yes, I've looked at the antiflood issue - it seems pretty straightforward to add in, but I'm thinking let's wait if/until the existing two pull requests get merged if/before tackling that one. It just gets a little messy with multiple open PRs. Is that OK?

**Comment by Eldenroot** [comment]
Ok, nice, good job! Better to wait with another PR, merge conflicts are waste of time :)

**Comment by SvePu** [comment]
Merged ... Thanks @lairdshaw

**Comment by Eldenroot** [comment]
Thank you both for your contribution and review!

**Pull request merged**
